apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-deployment
  labels:
    app: mail # cosmetic, or for org / filter / tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mail # used for service routing
  template:
    metadata:
      labels:
        app: mail # used for service routing
    spec:
      containers:
        - name: mail
          image: marcusbory/mail:latest
          env:
            - name: MAIL_DOMAIN
              value: ""
            - name: MAIL_HOST
              value: localhost
            - name: MAIL_PORT
              value: "1025"
            - name: MAIL_ENCRYPTION
              value: none
            - name: MAIL_USERNAME
              value: ""
            - name: MAIL_PASSWORD
              value: ""
            - name: FROM_NAME
              value: "No-Reply @ Company Name"
            - name: FROM_ADDRESS
              value: "no-reply@mydomain.com"
          ports:
            - containerPort: 80 # mail listens on :80 inside the container (mail-service/main.go)

---

apiVersion: v1
kind: Service
metadata:
  name: mail-service # must match the name of the service in the mail-service/
spec:
  selector:
    app: mail # used for service routing (as above)
  ports:
    - protocol: TCP
      name: main-port
      port: 80
      targetPort: 80
  type: ClusterIP # by default, ClusterIP is used
