version: "3"

services:
  broker-service:
    build:
      context: ../broker-service # folder containing resources
      dockerfile: ../broker-service/broker-service.dockerfile # Dockerfile to use
    restart: always
    ports:
      - "8080:80" # map the container port 80 to the host (ME) port 8080
    deploy:
      mode: replicated
      replicas: 1 # can't listen to multiple ports on the same host

  authentication-service:
    build:
      context: ../authentication-service
      dockerfile: ../authentication-service/authentication-service.dockerfile
    restart: always
    ports:
      - "8082:80" # Docker allows multiple services to listen to the same port (80)
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: >-
        host=postgres port=5432 user=postgres password=postgres dbname=database
        sslmode=disable timezone=UTC connect_timeout=5
    depends_on:
      - postgres
      # NOTE: DSN can be listed in object form (DSN:"...") or list form (- DSN="...")
      # Note: List form cannot have line break - will spoil parsing

      # Host - service connected to
      # Port - port of the service
      # DBname - name of the database
      # SSLmode - SSL mode to connect to the database (disabled because we're not using SSL)
      # Timezone - timezone to use for the database
      # Connect_timeout - timeout to connect to the database

  postgres:
    image: postgres:14.2
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=database # name of the database, not using users because I want portability
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/ # just keeping it at postgres-data folder

  logger-service:
    build:
      context: ../logger-service
      dockerfile: ../logger-service/logger-service.dockerfile # Dockerfile to use
    restart: always
    # No need ports because logger is used internally by the broker
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - mongo

  mongo:
    image: mongo:4.2.16-bionic
    ports:
      - "27017:27017"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - MONGO_INITDB_DATABASE=logs
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./mongo-data:/data/db # just keeping it at mongo-data folder
